[program:joggler]
directory=/home/gduthie/joggler
command=/home/gduthie/joggler/venv/bin/python /home/gduthie/joggler/transport-proxy.py
environment=JOGGLER_APP_DIR="/home/gduthie/joggler",JOGGLER_BIND_HOST="127.0.0.1",JOGGLER_PORT="8002"
user=gduthie
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/joggler.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
stdout_logfile=/var/log/supervisor/joggler.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
